version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: scripts/server
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    links:
      - db
    env_file: .env
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-file-format=Barracuda --innodb-file-per-table=true --innodb-large-prefix=true
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Japan
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
